### PR TITLE
Bump transformers bound

### PR DESCRIPTION
**Pull request by bgamari**

### CODE REVIEW

**Comment by bgamari** [comment]
Ping.

**Comment by cartazio** [comment]
@bgamari could probably stand a comonad < 5.1 bound bump too ?

**Comment by LeifW** [comment]
@cartazio I already bumped it to < 6 in https://github.com/ekmett/trifecta/pull/53

**Comment by cartazio** [comment]
thats not a release :)

**Comment by bgamari** [comment]
Indeed a release would be appreciated.

**Pull request merged**
