### PR TITLE
Allow blaze-html-0.10 and blaze-markup-0.9

### PR DESCRIPTION
**Pull request by phadej**

### CODE REVIEW

**Comment by RyanGlScott** [comment]
Hm, another possibility is that we could just drop support for `blaze-html` < 0.10 and `blaze-markup` < 0.9. Is there any advantage to using CPP hackery to keep such a broad range of supported versions?

**Comment by RyanGlScott** [comment]
Er, sorry, I mean `blaze-markup` < 0.8. (I don't think there's anything specific to `blaze-html-0.9` that we'd need to change, now that I look more closely).

**Comment by phadej** [comment]
There is plenty of package depending on `blaze-`:
- http://packdeps.haskellers.com/reverse/blaze-markup
- http://packdeps.haskellers.com/reverse/blaze-html

Having wider bounds will help with overall transition. The hack is indeed: a hack, but it's quite local.

**Comment by phadej** [comment]
... I can make it prettier though.

**Comment by RyanGlScott** [comment]
If you think this will help with the transition, I can certainly merge as-is.

How would you make this prettier, though, I wonder? :)

**Comment by phadej** [comment]
Now it is a bit prettier. Less smelly. :)

**Comment by phadej** [comment]
@RyanGlScott It helps in the sense, that new trifecta can enter the next Stackage nightly, not waiting for the whole `blaze-html` issue to be resolved.

**Comment by RyanGlScott** [comment]
Sounds good to me. Thanks, @phadej!

**Comment by RyanGlScott** [comment]
I've uploaded [`trifecta-1.6.2.1`](http://hackage.haskell.org/package/trifecta-1.6.2.1) to Hackage with this fix.

**Comment by phadej** [comment]
Thanks!

**Pull request merged**
