### PR TITLE
race combinator

### PR DESCRIPTION
**Pull request by mikeplus64**
I really don't know what I'm doing. But it works for my purposes, seemingly.

### CODE REVIEW

**Comment by ekmett** [comment]
This has different semantics than the race combinator I'm looking for. You really want to take the longest parse, which needs the 4th continuation to know how much it has consumed so we can compare. This requires more rejiggering.

**Comment by mikeplus64** [comment]
Ah, right.

> longest parse
Or multiple parses at the same location?

**Comment by ekmett** [comment]
What I do elsewhere is take longest parse if they differ and the left parse (merging the expected tokens) if they the same.

This ensures that if you just use the "expected tokens" at any step you can always enumerate all possible parses.

**Comment by mikeplus64** [comment]
Could/should ErrInfo be removed from Parser, but kept in trifecta except as a possible/default "pretty" version of an Err? As an aside, that would make it easy to for me to have e.g. HTML output. (At the moment my work project uses an ANSI terminal → HTML javascript library which is not that ideal. It would also make implementing lists of suggestions a little easier)

**Comment by ekmett** [comment]
There has been some discussion of rebasing ansi-wl-pprint on
wl-pprint-extras, extended with code to make it a viable replacement for
annotated-wl-pprint.

That said, I'm not in a hurry to switch trifecta over to a super-general
document type and parameterize everything with the annotation type, because
it would drastically complicate the API.

I built a set of parser combinators before that could let you specify the
auto-completion hooks for each of the expected token types, letting you tab
complete everything legal at a given point. I've yet to port most of that
code over to Haskell, though.

**Comment by mikeplus64** [comment]
I've done some more jiggering, just adding the current (I think) Delta and Err to the 4th continuation. But it doesn't check for the longest parse or anything, because I'm not sure how to do that. Is this on the right track?

**Comment by mikeplus64** [comment]
I've tried following through on removing ErrInfo from Parser. It /seems/ OK. I really don't know what I'm doing with finalDelta, deltas etc., though.

**Comment by mikeplus64** [comment]
Yes, lol, that last commit is really broken.

**Pull request closed without merging**
