### PR TITLE
CI: Use newer version of cabal-docspec

### PR DESCRIPTION
**Pull request by RyanGlScott**

### CODE REVIEW

**Comment by RyanGlScott** [comment]
@phadej, do you understand why the doctests fail with the newer version of `cabal-docspec`? It's not very obvious from the GitHub Actions output, but the failures arise due to whitespace-related differences:

github

Bisecting reveals that this behavior was introduced in https://github.com/phadej/cabal-extras/commit/d272839f84f9d992565e28f3b5f4479a05b16d26.

**Comment by phadej** [comment]
newer `cabal-docspec` doesn't strip trailing whitespace. But apparently `trifecta` generates some.

If we'll reintroduce (trailing) whitespace ignore functionality to `cabal-docspec`, it should be behind the flag.

**Comment by RyanGlScott** [comment]
Ah, I see. Admittedly, I'm not sure how difficult it would be to have `trifecta` not produce trailing whitespace, so having the ability not to strip trailing whitespace from `cabal-docspec` as an optional configuration would be nice.

**Comment by phadej** [comment]
https://github.com/phadej/cabal-extras/pull/129

For the record, I was positively surprised of myself that it was `cabal-docspec` diff which colored the trailing whitespace. I already forgot I did that, and thought that you had some tool to highlight it on the screenshot. But good thing it was there, otherwise it could been hard to figure out what happens here.

**Comment by RyanGlScott** [comment]
Thanks! Let's try it out here.

**Comment by RyanGlScott** [comment]
The CI finally passes. Woohoo!

**Comment by phadej** [comment]
Is there something wrong with this repo? This PR is not (marked) as merged. and the `newer-cabal-docspec` seems to be set as default brannch?

**Comment by RyanGlScott** [comment]
I'm not sure if I understand your question. The default branch still appears to be `master`, unless I am mistaken?

If you're asking why I haven't merged this yet: no particular reason. I can get this merged soon.

**Pull request merged**
